services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebot-app
    env_file:
      - .env
    environment:
      VALKEY_HOST: valkey
      VALKEY_PORT: "6379"
      QDRANT_HOST: vector_db
      QDRANT_PORT: "6333"
      QDRANT_URL: http://vector_db:6333
    depends_on:aara
      - valkey
      - vector_db
    ports:
      - "8000:8000"
    restart: unless-stopped

  valkey:
    image: valkey/valkey
    container_name: codebot-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

  vector_db:
    image: qdrant/qdrant
    container_name: codebot-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  valkey_data:
  qdrant_data:


# services:
#   valkey:
#     image: valkey/valkey
#     ports:
#       - 6379:6379


#   vector_db:
#     image: qdrant/qdrant
#     ports:
#       - 6333:6333