"""add repository model

Revision ID: 10c2c4fa2b65
Revises: 912c7e3e3b41
Create Date: 2026-06-01 23:28:26.592063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c2c4fa2b65'
down_revision: Union[str, Sequence[str], None] = '912c7e3e3b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pull_requests', sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_pull_requests_tenant_id'), table_name='pull_requests')
    op.drop_constraint(op.f('uq_pull_requests_tenant_repo_pr'), 'pull_requests', type_='unique')
    op.create_unique_constraint('uq_pull_requests_tenant_repo_pr', 'pull_requests', ['repo_id', 'pr_number'])
    op.drop_column('pull_requests', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_pull_requests_tenant_repo_pr', 'pull_requests', type_='unique')
    op.create_unique_constraint(op.f('uq_pull_requests_tenant_repo_pr'), 'pull_requests', ['tenant_id', 'repo_id', 'pr_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pull_requests_tenant_id'), 'pull_requests', ['tenant_id'], unique=False)
    op.drop_column('pull_requests', 'merged_at')
    op.drop_column('pull_requests', 'closed_at')
    # ### end Alembic commands ###
