"""initial

Revision ID: 13d2e99eb25e
Revises: 
Create Date: 2026-05-09 22:44:04.510557

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d2e99eb25e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', 'MERGED', name='pr_state_enum'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_branch', sa.String(length=255), nullable=False),
    sa.Column('target_branch', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'repo_id', 'pr_number', name='uq_pull_requests_tenant_repo_pr')
    )
    op.create_index('ix_pull_requests_repo_pr', 'pull_requests', ['repo_id', 'pr_number'], unique=False)
    op.create_index('ix_pull_requests_tenant_id', 'pull_requests', ['tenant_id'], unique=False)
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('session_label', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('primary_auth_provider', sa.String(length=32), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_details_email'), 'user_details', ['email'], unique=True)
    op.create_index(op.f('ix_user_details_public_id'), 'user_details', ['public_id'], unique=True)
    op.create_index(op.f('ix_user_details_session_label'), 'user_details', ['session_label'], unique=True)
    op.create_index(op.f('ix_user_details_user_type'), 'user_details', ['user_type'], unique=False)
    op.create_table('vector_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', VECTOR(dim=1536), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_data_user_id'), 'vector_data', ['user_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_identity_provider_user')
    )
    op.create_index(op.f('ix_auth_identities_provider'), 'auth_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identities_provider_email'), 'auth_identities', ['provider_email'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('client_session_id', sa.String(length=128), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_client_session_id'), 'chat_threads', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('review_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='review_job_status_enum'), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_jobs_pr_id_queued_at', 'review_jobs', ['pr_id', 'queued_at'], unique=False)
    op.create_index('ix_review_jobs_status_queued_at', 'review_jobs', ['status', 'queued_at'], unique=False)
    op.create_table('review_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('totals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_info_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_method', sa.String(length=32), nullable=False),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('client_session_id', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('message_limit', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_auth_method'), 'user_sessions', ['auth_method'], unique=False)
    op.create_index(op.f('ix_user_sessions_client_session_id'), 'user_sessions', ['client_session_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_session_token_hash'), 'user_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('artifact_refs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_type', sa.Enum('RAW_DIFF', 'PROMPT', 'MODEL_RESPONSE', 'REPORT_EXPORT', 'LOG', 'OTHER', name='artifact_type_enum'), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['review_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'artifact_type', 'artifact_uri', name='uq_artifact_refs_job_type_uri')
    )
    op.create_index('ix_artifact_refs_job_id_type', 'artifact_refs', ['job_id', 'artifact_type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('code_context', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_status'), 'chat_messages', ['status'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='finding_severity_enum'), nullable=False),
    sa.Column('category', sa.Enum('SECURITY', 'BUG', 'PERFORMANCE', 'STYLE', 'MAINTAINABILITY', 'TEST', 'DOCS', 'OTHER', name='finding_category_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['review_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_findings_report_id', 'review_findings', ['report_id'], unique=False)
    op.create_index('ix_review_findings_severity_category', 'review_findings', ['severity', 'category'], unique=False)
    op.create_table('web_search_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_search_runs_message_id'), 'web_search_runs', ['message_id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_query'), 'web_search_runs', ['query'], unique=False)
    op.create_index(op.f('ix_web_search_runs_status'), 'web_search_runs', ['status'], unique=False)
    op.create_index(op.f('ix_web_search_runs_thread_id'), 'web_search_runs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_web_search_runs_user_id'), 'web_search_runs', ['user_id'], unique=False)
    op.create_table('web_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['web_search_runs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_sources_domain'), 'web_sources', ['domain'], unique=False)
    op.create_index(op.f('ix_web_sources_message_id'), 'web_sources', ['message_id'], unique=False)
    op.create_index(op.f('ix_web_sources_run_id'), 'web_sources', ['run_id'], unique=False)
    op.create_index(op.f('ix_web_sources_thread_id'), 'web_sources', ['thread_id'], unique=False)
    op.create_index(op.f('ix_web_sources_user_id'), 'web_sources', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_sources_user_id'), table_name='web_sources')
    op.drop_index(op.f('ix_web_sources_thread_id'), table_name='web_sources')
    op.drop_index(op.f('ix_web_sources_run_id'), table_name='web_sources')
    op.drop_index(op.f('ix_web_sources_message_id'), table_name='web_sources')
    op.drop_index(op.f('ix_web_sources_domain'), table_name='web_sources')
    op.drop_table('web_sources')
    op.drop_index(op.f('ix_web_search_runs_user_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_thread_id'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_status'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_query'), table_name='web_search_runs')
    op.drop_index(op.f('ix_web_search_runs_message_id'), table_name='web_search_runs')
    op.drop_table('web_search_runs')
    op.drop_index('ix_review_findings_severity_category', table_name='review_findings')
    op.drop_index('ix_review_findings_report_id', table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_status'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_artifact_refs_job_id_type', table_name='artifact_refs')
    op.drop_table('artifact_refs')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_client_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_auth_method'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('review_reports')
    op.drop_index('ix_review_jobs_status_queued_at', table_name='review_jobs')
    op.drop_index('ix_review_jobs_pr_id_queued_at', table_name='review_jobs')
    op.drop_table('review_jobs')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_client_session_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider_email'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_vector_data_user_id'), table_name='vector_data')
    op.drop_table('vector_data')
    op.drop_index(op.f('ix_user_details_user_type'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_session_label'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_public_id'), table_name='user_details')
    op.drop_index(op.f('ix_user_details_email'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index('ix_pull_requests_tenant_id', table_name='pull_requests')
    op.drop_index('ix_pull_requests_repo_pr', table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_table('documents')
    # ### end Alembic commands ###
