"""add cascade delete to foreign keys

Revision ID: 2ef7e47863d3
Revises: 81c2f9f31af9
Create Date: 2026-06-09 23:28:10.620091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef7e47863d3'
down_revision: Union[str, Sequence[str], None] = '81c2f9f31af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('repo_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'repo_id')
    # ### end Alembic commands ###
