"""add cascade delete to foreign keys

Revision ID: 81c2f9f31af9
Revises: 3863dc99faa5
Create Date: 2026-06-09 23:23:54.385310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c2f9f31af9'
down_revision: Union[str, Sequence[str], None] = '3863dc99faa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pull_requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pull_requests', 'user_details', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.drop_column('pull_requests', 'user_id')
    op.drop_table('repositories')
    # ### end Alembic commands ###
