"""add pr action field

Revision ID: 9ef3059f98d4
Revises: 6a7d11cbef3c
Create Date: 2026-06-23 08:35:00.418372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef3059f98d4'
down_revision: Union[str, Sequence[str], None] = '6a7d11cbef3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('pr_action', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'pr_action')
    # ### end Alembic commands ###
