"""change chate user table name to user details

Revision ID: e62a22af6969
Revises: 0a6f1f1d9d2b
Create Date: 2026-04-01 13:48:12.858079
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e62a22af6969"
down_revision = "0a6f1f1d9d2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_details", "public_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "user_details",
        "user_type",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("'guest'::character varying"),
    )
    op.alter_column(
        "user_details",
        "primary_auth_provider",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("'guest'::character varying"),
    )
    op.alter_column(
        "user_details",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_details",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_details",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_details",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "user_details",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_details",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_details",
        "primary_auth_provider",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
        existing_server_default=sa.text("'guest'::character varying"),
    )
    op.alter_column(
        "user_details",
        "user_type",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
        existing_server_default=sa.text("'guest'::character varying"),
    )
    op.alter_column(
        "user_details", "public_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    # ### end Alembic commands ###
