"""add cascade delete to foreign keys

Revision ID: eb78e3cc5db0
Revises: 2ef7e47863d3
Create Date: 2026-06-09 23:51:31.468394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb78e3cc5db0'
down_revision: Union[str, Sequence[str], None] = '2ef7e47863d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('owner', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('default_branch', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'repositories', 'user_details', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'is_active')
    op.drop_column('repositories', 'default_branch')
    op.drop_column('repositories', 'owner')
    op.drop_column('repositories', 'full_name')
    op.drop_column('repositories', 'user_id')
    # ### end Alembic commands ###
