"""create test db column for leanr sql alchemy

Revision ID: ed9965c5b40c
Revises: 41a73b7102d9
Create Date: 2026-05-18 21:33:53.436448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9965c5b40c'
down_revision: Union[str, Sequence[str], None] = '41a73b7102d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'test')
    # ### end Alembic commands ###
